### PR TITLE
PPS 2021 refactor

### LINKED ISSUE #56: Refactor utils module
#### Problem description

When we no longer need version 2018 we can refactor the utils module and remove functions: get_outputfiles, filter4oldfiles, get_xml_outputfiles, filter4oldfiles, create_xml_timestat_from_scene, get_time_control_ascii_filename, get_time_control_ascii_filename_candidates, get_product_statistics_files. And refactor the ones that are still needed.

### PR DESCRIPTION
**Pull request by ninahakansson**
Update the code to support only PPS-2021 and drop support for PPS 2014. The main thing is that the pps runner need only the level1c file to run. The NWP preparation is now in a separate runner. Some refactoring, with more subroutines in prepare_nwp

 - [x] Closes #56 
 - [x] Tests added 
 - [x] Tests passed: Passes ``pytest nwcsafpps_runner`` 
 - [x] Passes ``flake8 nwcsafpps_runner`` 
 - [ ] Fully documented

### CODE REVIEW

**Review by pnuu — COMMENTED** [review]
Just couple of quick comments:
* `pps_runner.py` is deleted and `pps2018_runner.py` is modified although the description says v2014 and v2018 support are dropped. Shouldn't it be the other way around?
* the example configs for v2014 and v2018 should be deleted for clarity if they are not supported any more
* `setup.py` installs the v2018 runner

**Comment by ninahakansson** [comment]
Thanks for the comments @pnuu! The pps_runner.py was for version 2014 only. The pps2018_runner.py was for version 2018 and forward. I can rename the pps2018_runner.py to pps_runner.py as there is now only one runner. I will have a look at the config files too.

File: bin/level1c_runner.py [hunk 1]
```diff
@@ -24,15 +24,14 @@
...
-import sys
 import signal
 
 from posttroll.subscriber import Subscribe
 from posttroll.publisher import Publish
 from nwcsafpps_runner.logger import setup_logging
 from nwcsafpps_runner.message_utils import publish_l1c, prepare_l1c_message
 from nwcsafpps_runner.l1c_processing import L1cProcessor
-from nwcsafpps_runner.l1c_processing import ServiceNameNotSupported
+# from nwcsafpps_runner.l1c_processing import ServiceNameNotSupported
```
Comment (adybbroe) [inline bin/level1c_runner.py:34]:
```suggestion
```

File: nwcsafpps_runner/tests/test_utils.py
Comment (adybbroe) [inline nwcsafpps_runner/tests/test_utils.py:1]: All this functionality on finding output files is being removed now? Is that not needed anymore? Can you just help explain the purpose?

Comment (adybbroe) [reply nwcsafpps_runner/tests/test_utils.py:1]: Ok, maybe I get it, so changing the runner to only work on level-1c files, a lot of complexity is not needed anymore, is it so?

File: setup.py [hunk 2]
```diff
@@ -59,9 +59,10 @@
       license='GPLv3',
       packages=find_packages(),
       scripts=['bin/pps_runner.py',
+               'bin/run_nwp_preparation.py',
                'bin/level1c_runner.py', ],
       data_files=[],
-      install_requires=['posttroll', 'trollsift', 'pygrib', ],
+      install_requires=['posttroll', 'trollsift', 'pygrib', 'six'],
```
Comment (adybbroe) [inline setup.py]: We should be able to scratch `six` now shouldn't we?

File: bin/run_nwp_preparation.py [hunk 3]
```diff
@@ -41,9 +41,8 @@
 
 def prepare_and_publish(pub, options, flens):
     config_file_name = options.config_file
-    starttime = datetime.utcnow() - timedelta(days=1)
+    starttime = datetime.utcnow() - timedelta(days=8)
```
Comment (adybbroe) [inline bin/run_nwp_preparation.py:45]: Should it really check for "new" files for the last 8 days?

File: nwcsafpps_runner/publish_and_listen.py [hunk 4]
```diff
@@ -51,7 +51,7 @@ def run(self):
         LOG.debug("Subscribe topics = %s", str(self.subscribe_topics))
         with posttroll.subscriber.Subscribe("", self.subscribe_topics, True) as subscr:
 
-            for msg in subscr.recv(timeout=90):
+            for msg in subscr.recv():
```
Comment (adybbroe) [inline nwcsafpps_runner/publish_and_listen.py:54]: Not sure why we had a timeout of 90 seconds before, but is it safe to change this? Why was this needed?

**Review by adybbroe — COMMENTED** [review]
Thanks a lot for the cleaning and refactoring, looks like  the code is moving in the right direction, but also hard to judge with som many changes. I have a few questions. Otherwise I am good with this

File: nwcsafpps_runner/tests/test_config.py [hunk 5]
```diff
@@ -126,9 +125,9 @@ def test_read_pps_runner_config(self, gethostname, config):
         """Test loading and initialising the yaml config"""
         gethostname.return_value = "my.local.host"
         config.return_value = self.config_pps_complete
-        myconfig_filename = '/tmp/my/config/file'
+        myconfig_filename = '/tmp/my/config/file.yaml'
```
Comment (adybbroe) [inline nwcsafpps_runner/tests/test_config.py:128]: Should we introduce pathlib here perhaps, getting rid of the codefactor warning?

File: nwcsafpps_runner/tests/test_utils.py
Comment (ninahakansson) [reply nwcsafpps_runner/tests/test_utils.py:1]: Yes, I think that is the key change!

File: bin/run_nwp_preparation.py (hunk 3 above)
Comment (ninahakansson) [reply bin/run_nwp_preparation.py:45]: Oups, checked in this by mistake :)!

File: nwcsafpps_runner/publish_and_listen.py (hunk 4 above)
Comment (ninahakansson) [reply nwcsafpps_runner/publish_and_listen.py:54]: I removed it because the patched subscriber did not have the timeout keyword. I am not sure if it is safe to remove.

Comment (mraspaud) [reply nwcsafpps_runner/publish_and_listen.py:54]: The timeout is needed I think when the thread is shut down. Maybe something we need in the patched_subscriber then.

File: nwcsafpps_runner/tests/test_config.py (hunk 5 above)
Comment (mraspaud) [reply nwcsafpps_runner/tests/test_config.py:128]: maybe tmp_path can be used here!

File: nwcsafpps_runner/tests/test_config.py [hunk 6]
```diff
@@ -106,9 +105,9 @@ def setUp(self):
     def test_read_lvl1c_runner_config(self, config):
         """Test loading and initialising the yaml config"""
         config.return_value = self.config_lvl1c_complete
-        myconfig_filename = '/tmp/my/config/file'
+        myconfig_filename = '/tmp/my/config/file.yaml'
```
Comment (mraspaud) [inline nwcsafpps_runner/tests/test_config.py:108]: how about tmp_path?

File: bin/run_nwp_preparation.py [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+from nwcsafpps_runner.prepare_nwp import update_nwp
+from nwcsafpps_runner.utils import NwpPrepareError
+from posttroll.publisher import Publish
+from nwcsafpps_runner.message_utils import publish_l1c, prepare_nwp_message
+
+NWP_FLENS = [6, 9, 12, 15, 18, 21, 24]
+
+LOG = logging.getLogger('nwp-preparation')
+
+# datetime.datetime.utcnow => datetime.datetime.now(datetime.UTC) ~python 3.12
```
[the remark this answers is not in the document]
Comment (ninahakansson) [reply bin/run_nwp_preparation.py:40]: Yes, the datetime.datetime.now(datetime.UTC) is working in python 3.12 but in 3.9 I get ```AttributeError: module 'datetime' has no attribute 'UTC'```. The datetime.datetime.now(datetime.UTC) will also need some changes in other parts of the code as it is not expecting timezone-aware objects. Currently I get a warning in 3.12: ```DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).```
